const now = new Date().toISOString();

export const emptyData = {
  projects: [],
  projectFolders: [],
  projectFiles: [],
  projectFeedback: [],
  projectComments: [],
  fileComments: [],
  projectUpdates: [],
  chatMessages: [],
  activityLogs: [],
  ideas: [],
  ideaComments: [],
  showcases: [],
  showcaseFeedback: [],
};

export const seedData = {
  projects: [
    {
      id: "project-1",
      title: "AI 급식 추천 앱",
      description: "학생들이 AI로 만든 웹앱입니다. 파일을 공유하고 함께 개선합니다.",
      category: "웹앱",
      owner_name: "Mina",
      collaborators: ["Joon", "Sungmin"],
      tags: ["학생", "AI빌드", "React"],
      visibility: "public",
      status: "진행 중",
      likes: 8,
      download_count: 3,
      fork_count: 1,
      original_project_id: null,
      fork_author: null,
      forked_at: null,
      created_at: now,
      updated_at: now,
    },
  ],
  projectFolders: [
    {
      id: "folder-1",
      project_id: "project-1",
      name: "src",
      folder_path: "",
      created_by: "Mina",
      created_at: now,
      updated_at: now,
    },
  ],
  projectFiles: [
    {
      id: "file-1",
      project_id: "project-1",
      folder_path: "src",
      resource_type: "code",
      original_name: "App.jsx",
      file_name: "App.jsx",
      mime_type: "text/jsx",
      size_bytes: 86,
      storage_path: null,
      public_url: null,
      external_url: null,
      version_group: "src/App.jsx",
      version_number: 1,
      created_by: "Mina",
      download_count: 1,
      content: "function App() {\n  return <main>Hello A&I</main>;\n}\n\nexport default App;\n",
      created_at: now,
      updated_at: now,
    },
    {
      id: "file-2",
      project_id: "project-1",
      folder_path: "",
      resource_type: "code",
      original_name: "README.md",
      file_name: "README.md",
      mime_type: "text/markdown",
      size_bytes: 92,
      storage_path: null,
      public_url: null,
      external_url: null,
      version_group: "README.md",
      version_number: 1,
      created_by: "Mina",
      download_count: 2,
      content: "# AI 급식 추천 앱\n\nAI로 빠르게 만든 학생용 메뉴 추천 프로젝트입니다.\n",
      created_at: now,
      updated_at: now,
    },
  ],
  projectFeedback: [
    {
      id: "feedback-1",
      project_id: "project-1",
      author_name: "Joon",
      feedback_type: "suggestion",
      body: "처음 들어온 사용자가 바로 메뉴를 고를 수 있게 시작 화면을 줄이면 좋겠습니다.",
      parent_feedback_id: null,
      created_at: now,
      updated_at: now,
    },
  ],
  projectComments: [],
  fileComments: [
    {
      id: "file-comment-1",
      project_id: "project-1",
      file_id: "file-1",
      author_name: "Joon",
      body: "첫 화면 문구를 실제 프로젝트 이름으로 바꾸면 더 좋겠습니다.",
      line_number: 2,
      parent_comment_id: null,
      resolved: false,
      created_at: now,
      updated_at: now,
    },
  ],
  projectUpdates: [
    {
      id: "update-1",
      project_id: "project-1",
      author_name: "Mina",
      title: "첫 번째 공유",
      body: "기본 화면과 README를 올렸습니다.",
      created_at: now,
      updated_at: now,
    },
  ],
  chatMessages: [],
  activityLogs: [
    {
      id: "activity-1",
      project_id: "project-1",
      actor_name: "Mina",
      action_type: "project_created",
      message: "프로젝트가 생성되었습니다.",
      created_at: now,
    },
  ],
  ideas: [
    {
      id: "idea-1",
      title: "캠퍼스 AI 빌드룸",
      category: "커뮤니티",
      author_name: "Jiwon",
      body: "학생들이 AI로 만든 프로젝트를 올리고 같이 개선하는 공간입니다.",
      upvotes: 12,
      created_at: now,
    },
  ],
  ideaComments: [],
  showcases: [],
  showcaseFeedback: [],
};
